collections_config:
  pages:
    icon: 'wysiwyg'
    schemas:
      default:
        path: site/schemas/page.html
  projects:
    icon: 'work_outline'
    subtext_key: subtitle
    schemas:
      default:
        path: site/schemas/project.md
  testimonials:
    icon: 'format_quote'
    subtext_key: position
    sort:
      key: name
    sort_options:
      - key: name
      - key: name
        order: desc
      - key: position
      - key: position
        order: desc
    _enabled_editors:
      - data
    schemas:
      default:
        path: site/schemas/testimonial.md
  posts:
    schemas:
      default:
        path: site/schemas/post.md

collection_groups:
  - heading: Content
    collections:
      - pages
      - projects
      - testimonials
  - heading: Blogging
    collections:
      - posts
      - drafts
  - heading: Settings
    collections:
      - data

# The rest of this structures definition will be
# populated by the bookshop-array-structures plugin.
_structures:
  content_blocks:
    style: modal
